version: "3"   #版本信息

services:
  # 富文本编辑器
  stackedit:
    restart: always
    build:
      context: ../dev
      dockerfile: node_11.15.0.Dockerfile
    #
    image: chenaimin/stackedit:1.0.1
    container_name: stackedit-dev
    privileged: true   #设置容器的权限为root
    ports:
      - "2222:22"
    environment:
      TZ: Asia/Shanghai
    tty: true
